### ISSUE TITLE
Theme not compatible with PHP 8

### ISSUE THREAD

**Issue by philouseb** [wpexplorer/wpex-adapt#10]
Hello,
Sorry in advance for my English.
Do you plan to update the theme to be compatible with php 8 ?
Thank you

**Comment by wpexplorer** [comment]
@philouseb

Hey this is AJ from WPExplorer (I'm actually a solo company)

The demo is using PHP 8.2 - https://wpexplorer-demos.com/adapt/ - without any issues. What error do you see on your site? If you want I can help you manually patch the site, just to fix the error.

These classic themes I made a while back because they aren't hosted on WP.org don't have automatic updates so it's possible your theme is outdated. I made them primarily with the thought that people would download them, rename them and use them on client sites with their own brand - thus not uploading them to WordPress.org - this way they won't get updates that would break client sites.

I actually just started doing big updates to all the themes this week. I've already updated the following:

- https://github.com/wpexplorer/wpex-elegant
- https://github.com/wpexplorer/wpex-corporate
- https://github.com/wpexplorer/wpex-today
- https://github.com/wpexplorer/wpex-powered
- https://github.com/wpexplorer/wpex-new-york/

And I will be updating the rest soon...

What I'm primarily doing in these updates is the following:

- Removing the admin panel that has some recommendations
- Removing the dashboard feeds
- Removing the default backlink in the footer copyright so instead it's just copyright [year] site name
- Removing any unnecessary post meta settings (in the case of Adapt this will include the portfolio "Post Media Alternative" field (so if you use that you may not want to update, once the update is available).
- Updating font awesome to version 6.0 - or if there is only a few icons being used, removing font awesome and using SVG icons instead
- Optimizing script loading.
- Updating theme image sizes to use 9999x9999 for the width and height to prevent cropping by default and instead using CSS to set image aspect ratios for the various images.
- Adding the required attribute to the search form.
- Removing html5 shiv file if it's being added.
- Removing old CSS for contact form 7.
- Removing old CSS that prevents focus styles.
- Adding CSS variable for the theme's accent color to make it easier for anyone to change the accent.
- Updating the style.css file to use direction aware properties for automatic RTL support.

So once the update is ready for Adapt (maybe next week) if these changes will affect your site then you would probably want to update manually instead. This way you can look at the changes made in the theme apply only the ones you want by updating the file via FTP or manually editing the code.

For the most part I am going through and making these updates so that the theme's can for the most part be archived as they won't need any updating in the future.

I'm focused mostly on my top selling theme - https://totalwptheme.com/ - and I am working on a free block theme with a premium upgrade. So I will have 1 big classic theme and 1 big block theme that I will primarily maintain. Any new free themes I do make, will be block themes as block themes won't require any sort of maintenance.

---

If you want, you can also pay me and I can help manually fix any issues on the site once you upgrade to PHP 8.

Feel free to email me directly to wpexplorer [at] gmail dot com if interested. I charge $75/hour. I can't imagine any fixes your site needs to take very much time at all, but I do have a minimum 1hr requirement for my custom work. So, if you have any special requests for your site we could fit them in. Right off the bat I see a couple console errors on your site that could be fixed, we could update the homepage icons to use SVG's so that they are retina ready and they load faster, logo could be optimized to be 12kb instead of 59kb...etc.
 
- AJ

ps: Sorry for the long reply!!!

**Comment by philouseb** [comment]
Thank you for your reply.
I created a child theme, without my child theme it works and as soon as I activate my child theme I get an error.
Here's the error I have:
---------------------
Fatal error: Uncaught Error: 

Call to undefined function create_function() in /Users/philseb/Gestion Pro/Site_Internet/Versions_Locales/graphistelibre_2023/wp-content/themes/wpex-adapt-child/functions.php:33 

Stack trace: #0 /Users/philseb/Gestion Pro/Site_Internet/Versions_Locales/graphistelibre_2023/wp-settings.php(668): include() #1 /Users/philseb/Gestion Pro/Site_Internet/Versions_Locales/graphistelibre_2023/wp-config.php(103): require_once('/Users/philseb/...') #2 /Users/philseb/Gestion Pro/Site_Internet/Versions_Locales/graphistelibre_2023/wp-load.php(50): require_once('/Users/philseb/...') #3 /Users/philseb/Gestion Pro/Site_Internet/Versions_Locales/graphistelibre_2023/wp-blog-header.php(13): require_once('/Users/philseb/...') #4 /Users/philseb/Gestion Pro/Site_Internet/Versions_Locales/graphistelibre_2023/index.php(17): require('/Users/philseb/...') #5 {main} thrown in /Users/philseb/Gestion Pro/Site_Internet/Versions_Locales/graphistelibre_2023/wp-content/themes/wpex-adapt-child/functions.php on line 33
---------------------
Thank you in advance

**Comment by philouseb** [comment]
Thank you for your reply.
I created a child theme, without my child theme it works and as soon as I activate my child theme I get an error.
Here's the error I have:
---------------------
Fatal error: Uncaught Error: Call to undefined function create_function() in /Users/philseb/Gestion Pro/Site_Internet/Versions_Locales/graphistelibre_2023/wp-content/themes/wpex-adapt-child/functions.php:33 Stack trace: #0 /Users/philseb/Gestion Pro/Site_Internet/Versions_Locales/graphistelibre_2023/wp-settings.php(668): include() #1 /Users/philseb/Gestion Pro/Site_Internet/Versions_Locales/graphistelibre_2023/wp-config.php(103): require_once('/Users/philseb/...') #2 /Users/philseb/Gestion Pro/Site_Internet/Versions_Locales/graphistelibre_2023/wp-load.php(50): require_once('/Users/philseb/...') #3 /Users/philseb/Gestion Pro/Site_Internet/Versions_Locales/graphistelibre_2023/wp-blog-header.php(13): require_once('/Users/philseb/...') #4 /Users/philseb/Gestion Pro/Site_Internet/Versions_Locales/graphistelibre_2023/index.php(17): require('/Users/philseb/...') #5 {main} thrown in /Users/philseb/Gestion Pro/Site_Internet/Versions_Locales/graphistelibre_2023/wp-content/themes/wpex-adapt-child/functions.php on line 33
---------------------
Thank you in advance

**Comment by philouseb** [comment]
I've found the solution.
Problem solved.
