### ISSUE TITLE
change naming of "newer" / "older"

### ISSUE THREAD

**Issue by Madsvj** [wpexplorer/wpex-adapt#3]
Hi,
I'm helping af friend with her wordpres website.
As her website is not a blog, we wan't to change the naming of the "newer" / "older" buttons or totally remove them.
Is that possible?
Example use: http://www.rensnak.dk/portfolio-item/i-gang-med-talerteknik/

**Comment by wpexplorer** [comment]
Sorry for never getting back to you, I wasn't getting my email notifications from github :(

So to change the text you can either place the single-portfolio.php file into a child theme and modify it the text is near the top.

Or you can use the gettext filter so you can rename these easily via a child theme's functions.php file using code like this:

```
add_filter( 'gettext', function( $translated_text, $text, $domain ) {
	switch ( $translated_text ) {
		case 'Newer' :
			$translated_text = __( 'Your custom newer text', 'wpex-adapt' );
		break;
		case 'Older' :
			$translated_text = __( 'Your custom older text', 'wpex-adapt' );
		break;
	}
	return $translated_text;
}, 20, 3 );
```

This is the better method because if you ever have to update the core theme you won't lose changes and you don't have to replace an entire file ;)

- AJ
